version: '3.8'

services:
  samair-st:
    build: .
    ports:
      - "3001:3001"
    volumes:
      # Монтируем директорию данных для сохранения между перезапусками
      - ./server/data:/app/server/data
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/email-status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 